# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.CharField(max_length=230)),
                ('slogan', models.TextField(max_length=120)),
                ('description', models.TextField()),
                ('details', models.TextField()),
                ('picture', models.CharField(max_length=240)),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
